**Original Folder:** suicide_watch-database\PRAW\meta_data

In [ ]:
import pandas as pd

In [3]:
available_batches = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
df_all = pd.DataFrame()
for batch_number in available_batches:
    df = pd.read_csv(f"batch{batch_number}_metadata_comments.csv")
    df_all = pd.concat([df_all, df], ignore_index=True)
df_all

,username,subreddit,body,created_utc,score
0,---feelingalone---,SuicideWatch,I was an athlete in undergrad and the meds mak...,1.282797e+09,1
1,---feelingalone---,SuicideWatch,I like this. I've always enjoyed helping peop...,1.282797e+09,2
2,---feelingalone---,SuicideWatch,I went off the meds because I got better. I h...,1.282796e+09,1
3,---feelingalone---,SuicideWatch,"My school got shot up by a guy, killed a bunch...",1.282796e+09,2
4,---feelingalone---,SuicideWatch,I was on meds for 2 years and have been off th...,1.282795e+09,1
...,...,...,...,...,...
45721488,brooklynhils,confession,I would have been saved!! Can't stop laughing....,1.569767e+09,3
45721489,brooklynhils,confession,"Thanks man, your post made me remember a time ...",1.569746e+09,10
45721490,brooklynhils,insanepeoplefacebook,Must insert at least ¾ mashed potato into each...,1.569216e+09,2
45721491,brooklynhils,NatureIsFuckingLit,"Me, realizing my glove is inside out.",1.568494e+09,1
45721492,Low-Strength0806,SuicideWatch,Thank you. This comment means more to me than ...,1.654765e+09,1

In [4]:
df_all.to_csv("all_batches_metadata_comments.csv", index=False)

In [2]:
available_batches = [1, 2, 3, 4, 5, 6, 7, 8, 11]
df_all = pd.DataFrame()
for batch_number in available_batches:
    df = pd.read_csv(f"batch{batch_number}_metadata_posts.csv")
    df_all = pd.concat([df_all, df], ignore_index=True)
df_all

,username,subreddit,title,selftext,created_utc,score,upvote_ratio,num_comments
0,---feelingalone---,SuicideWatch,I have almost no support structure,My girlfriend left me for one of my friends be...,1.282791e+09,12,0.94,24
1,-anonymously,SuicideWatch,no one knows this about me,i don't want anyone to know this about me but ...,1.395478e+09,2,0.63,12
2,-crave,OopsThatsDeadly,Need assistance on how to remove this faster -...,NaN,1.741912e+09,0,0.42,7
3,-crave,tonightsdinner,Homemade chicken and tofu satay with homemade ...,NaN,1.734306e+09,8,0.91,0
4,-crave,tonightsdinner,"Main course tonight? Marry Me Soy Curls, one o...",NaN,1.726700e+09,11,0.79,3
...,...,...,...,...,...,...,...,...
6254202,brooklynhils,SuicideWatch,an interesting title,I've been lurking here a while now and was abo...,1.654762e+09,3,1.00,3
6254203,brooklynhils,CheatersConfronted,"Pinch or Hickey?Side of my, 28m so's neck. I t...",NaN,1.653628e+09,1,1.00,0
6254204,brooklynhils,DermatologyQuestions,Pinch vs Hickey (on the right side of my so's ...,NaN,1.653569e+09,1,1.00,3
6254205,burn_the_damnaccount,SuicideWatch,I’m thinking I’ve lost my fight,I’ve been struggling with mental illness for q...,1.654761e+09,1,1.00,0
6254206,Low-Strength0806,SuicideWatch,It's the little things that make me question m...,I'm so tired. Exhausted. Every day getting out...,1.654763e+09,3,0.81,3

In [ ]:
df_all.to_csv("all_batches_metadata_posts.csv", index=False, encoding="utf-8-sig")

In [ ]:
df_open = pd.read_csv("all_batches_metadata_posts.csv", encoding="utf-8-sig")

In [1]:
df_open

NameError: name 'df_open' is not defined